### ISSUE TITLE
Add opcode cache to PHP [2h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-lamp#3]
Opcode cache is the essential PHP performance optimization and we don't have any right now for the PHP installed by this Docker image. We could install `php5-xcache` and configure generous memory allowance to make sure a typical Drupal installation can fit.
Location of the webserver-related PHP config
`/usr/local/etc/php/conf.d`

**Comment by amitaibu** [comment]
I think you'll need to push it to docker hub for travis to take advantage of it. What your docker hub username?

**Comment by AronNovak** [comment]
Fortunately it's all automatic:
![lamp](https://cloud.githubusercontent.com/assets/114076/24538539/13317d6e-15ea-11e7-91ab-d3ba2c518d59.png)

https://hub.docker.com/r/gizra/drupal-lamp/builds/bsbm7pffdwgwtt7w6e6856n/
